### PR TITLE
Add Troubleshooting section

### PR DESCRIPTION
**Pull request by hamen**
I'm running this using WSL on Windows. I tried to run:

```shell
./gradlew spotlessApply
```
and I encountered some issue that would be worth nothing down to help more people.

### CODE REVIEW

**Comment by SigmanZero** [comment]
Hello, on Windows I believe you should use the `gradlew.bat` script instead.

**Comment by rock3r** [comment]
@hamen out of curiosity, did you check out the repo on Windows, and then ran into the issue when running Gradle from WSL? If that's the case, the easiest fix is _not_ to share repos between Windows and WSL — annoying, I know, but you're bound to run into many such line ending issues if you do. Ask me how I know 😆 

The alternative is to set the `core.autocrlf` property to false for the repo when checking out, but that will result in a repo that only works on Windows and not on WSL. Unfortunately, there is no easy way to set up a project on a shared folder that will work both for Windows and WSL — or at least, I have never found one. It's always either working for Windows, or WSL.

The solution you propose is ok but might result in git saying the file has changed.

**Comment by hamen** [comment]
I indeed cloned the repo using Android Studio. Unfortunately, I tried `core.autocrlf` unsuccessfully.
I understand that my solution could be considered suboptimal in the greater scheme, but it would be one less obstacle to receive external contributions to the project.

**Comment by rock3r** [comment]
I reckon it's useful but needs to be caveated with the "_if_ you're on Windows, _and_ you checked out the repo on Windows, _and_ you're trying to build it from WSL, then...". The issue, and the workaround you documented, is going to apply to any Gradle project, not just Socialite.

Arguably, it's a _very_ niche setup, and someone who is advanced enough to do this, should already have figured out how to fix this issue as it'll apply to all their projects in the same situation. Ultimately, it's up to the maintainers to decide whether this is relevant enough for the audience of this repo. It's not a bad addition, imo.

**Comment by SigmanZero** [comment]
Oops, thank you for the clarifications @hamen, I had misunderstood the issue.

**Comment by yaraki** [comment]
> I reckon it's useful but needs to be caveated with the "_if_ you're on Windows, _and_ you checked out the repo on Windows, _and_ you're trying to build it from WSL, then...". The issue, and the workaround you documented, is going to apply to any Gradle project, not just Socialite.
> 
> Arguably, it's a _very_ niche setup, and someone who is advanced enough to do this, should already have figured out how to fix this issue as it'll apply to all their projects in the same situation. Ultimately, it's up to the maintainers to decide whether this is relevant enough for the audience of this repo. It's not a bad addition, imo.

I agree with this. The situation is not specific to this project, so it feels weird to mention it in this readme.

**Pull request closed without merging**
